#!/bin/python3 -u

from os import system
from json import dumps

from i3ipc import Connection, Event

EWW = "/usr/local/bin/eww"
i3 = Connection()

def dump_list(l: list):
    return f"[{' '.join(repr(e) for e in l)}]"

workspace_classes = [""] * 10
print(list(filter(lambda workspace: workspace.focused, i3.get_workspaces()))[0].num)
# system(f"{EWW} update focused_workspace=\"{dump_list(workspace_classes)}\"")

def on_workspace_focus(self, e):
    # print(e.old.num, e.current.num)
    workspace_classes[e.old.num - 1] = ""
    workspace_classes[e.current.num - 1] = "focused"
    # system(f"{EWW} update workspace_classes=\"{dump_list(workspace_classes)}\"")
    print(e.current.num)

def on_workspace_init(self, e):
    print("What")

i3.on(Event.WORKSPACE_FOCUS, on_workspace_focus)
i3.on(Event.WORKSPACE_INIT, on_workspace_init)

i3.main()
