#!/bin/python3 -u

from os import system
from json import dumps

from i3ipc import Connection, Event

EWW = "/usr/local/bin/eww"
i3 = Connection()

def dump_list(l: list):
    return f"[{' '.join(repr(e) for e in l)}]"

print(list(filter(lambda workspace: workspace.focused, i3.get_workspaces()))[0].num)
# system(f"{EWW} update focused_workspace=\"{dump_list(workspace_classes)}\"")

def on_workspace_focus(self, e):
    # print(e.old.num, e.current.num)
    # system(f"{EWW} update workspace_classes=\"{dump_list(workspace_classes)}\"")
    print(e.current.num)

i3.on(Event.WORKSPACE_FOCUS, on_workspace_focus)

i3.main()
